# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BreakdownName', models.CharField(max_length=20)),
                ('LRemarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Breakdownlogin',
            fields=[
                ('LoginNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Result', models.CharField(max_length=10)),
                ('BreakdownType', models.CharField(max_length=20)),
                ('BreakdownLevel', models.CharField(max_length=20)),
                ('Line', models.CharField(max_length=20)),
                ('Site', models.CharField(max_length=20)),
                ('Coach', models.CharField(max_length=10)),
                ('Position', models.CharField(max_length=20)),
                ('BreakdownCount', models.IntegerField(max_length=3)),
                ('Keyboard', models.CharField(max_length=20)),
                ('Processor', models.CharField(max_length=20)),
                ('BreakdownDate', models.DateField()),
                ('LoginRemark', models.CharField(max_length=200)),
            ],
        ),
    ]
